language: php

cache:
    directories:
        - $HOME/.composer/cache

php:
#    - hhvm
    - nightly
    - '7.0'
    - '5.6'
    - '5.5'

env:
    - SYMFONY_VERSION="2.7.*"
    - SYMFONY_VERSION="2.8.*"
    - SYMFONY_VERSION="3.0.*"
    - SYMFONY_VERSION="3.1.*"

matrix:
    include:
        - php: 5.3
          env: SYMFONY_VERSION="2.7.*"
        - php: 5.3
          env: SYMFONY_VERSION="2.8.*"
        - php: 5.4
          env: SYMFONY_VERSION="2.7.*"
        - php: 5.4
          env: SYMFONY_VERSION="2.8.*"

before_install:
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install:
    - composer update --prefer-source --no-interaction $COMPOSER_FLAGS

script:
   - vendor/bin/phpunit
